### ISSUE TITLE
Costs of the materials

### ISSUE THREAD

**Issue by farfalk** [MKnierim/openbci-ceegrids#1]
First things first: thank you so much for sharing your approach!

I'm planning to reproduce your approach in the near future, but I'd like to know the costs (estimated is good enough) of the components and the materials to plan accordingly. Is it possible, and would it be meaningful to you, to list them in the materials section of the readme (https://github.com/MKnierim/openbci-ceegrids#materials)?

**Comment by MKnierim** [comment]
Sure, that seems like a good idea to me too! I have added material cost estimates to the section. Please be advised that these costs might still vary slightly, depending on whether you use manufacturing services or not (incl. material, labor, and postage costs). Also, if you'd prefer to get the materials sent to you altogether in a package, please take a look at this offer: https://exgtools.expeeeriments.io/
