### ISSUE TITLE
I can't make contact with the website administrator listed in the readme documents (expeeeriment.io）

### ISSUE THREAD

**Issue by SeanZhang99** [MKnierim/openbci-ceegrids#2]
I want to buy a kit and some more electrodes. But if I directly purchase them, I have to pay double package fees. Besides, I want to know more detail from the developer. I've tried to send emails according to their description in the website, but no response was given for few weeks. So if anyone knows how contact them please tell me. Thankyou!

**Comment by MKnierim** [comment]
Dear SeanZhang99, oh that is unfortunate. Upon checking with my mail provider, it appears that your message was not correctly delivered. However, I have received it and will reply to you by the end of the day!
